export const coursesData = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    category: "Web Development",
    image: "/images/courses/c1.jpg",
    instructor: "Alex Johnson",
    rating: 4.8,
    reviewCount: 1245,
    price: 89.99,
    originalPrice: 199.99,
    level: "All Levels",
    duration: "42h 30m",
    badges: ["Bestseller", "Top Rated"],
  },
  {
    id: 2,
    title: "Advanced JavaScript: From Fundamentals to Functional JS",
    category: "JavaScript",
    image: "/images/courses/c2.jpg",
    instructor: "Sarah Chen",
    rating: 4.9,
    reviewCount: 982,
    price: 79.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "28h 15m",
    badges: ["Hot & New"],
  },
  {
    id: 3,
    title: "Flutter & Dart: The Complete Guide",
    category: "Mobile Development",
    image: "/images/courses/c3.jpg",
    instructor: "Mark Williams",
    rating: 4.7,
    reviewCount: 843,
    price: 94.99,
    originalPrice: 189.99,
    level: "Beginner",
    duration: "32h 45m",
    badges: ["Bestseller"],
  },
  {
    id: 4,
    title: "Machine Learning A-Z: Hands-On Python & R",
    category: "Data Science",
    image: "/images/courses/c1.jpg",
    instructor: "Jessica Taylor",
    rating: 4.6,
    reviewCount: 1532,
    price: 129.99,
    originalPrice: 199.99,
    level: "Advanced",
    duration: "45h 20m",
    badges: ["Highest Rated"],
  },
  {
    id: 5,
    title: "The Complete React Developer Course",
    category: "Web Development",
    image: "/images/courses/c2.jpg",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 1089,
    price: 84.99,
    originalPrice: 169.99,
    level: "Intermediate",
    duration: "30h 10m",
    badges: ["Bestseller"],
  },
  {
    id: 6,
    title: "UX & UI Design Masterclass",
    category: "Design",
    image: "/images/courses/c3.jpg",
    instructor: "Emma Wilson",
    rating: 4.7,
    reviewCount: 756,
    price: 69.99,
    originalPrice: 139.99,
    level: "All Levels",
    duration: "24h 30m",
  },
  {
    id: 7,
    title: "AWS Certified Solutions Architect",
    category: "Cloud Computing",
    image: "/images/courses/c1.jpg",
    instructor: "David Miller",
    rating: 4.9,
    reviewCount: 1342,
    price: 119.99,
    originalPrice: 229.99,
    level: "Advanced",
    duration: "38h 15m",
    badges: ["Highest Rated", "Bestseller"],
  },
  {
    id: 8,
    title: "Python for Data Science and Machine Learning",
    category: "Data Science",
    image: "/images/courses/c2.jpg",
    instructor: "Rebecca Lee",
    rating: 4.8,
    reviewCount: 982,
    price: 89.99,
    originalPrice: 179.99,
    level: "Intermediate",
    duration: "36h 45m",
    badges: ["Top Rated"],
  },
  {
    id: 9,
    title: "The Complete Digital Marketing Course",
    category: "Marketing",
    image: "/images/courses/c3.jpg",
    instructor: "Thomas Clark",
    rating: 4.6,
    reviewCount: 1120,
    price: 94.99,
    originalPrice: 189.99,
    level: "Beginner",
    duration: "32h 15m",
  },
  {
    id: 10,
    title: "iOS App Development with Swift",
    category: "Mobile Development",
    image: "/images/courses/c1.jpg",
    instructor: "Jennifer Roberts",
    rating: 4.7,
    reviewCount: 876,
    price: 99.99,
    originalPrice: 199.99,
    level: "Intermediate",
    duration: "34h 20m",
  },
  {
    id: 11,
    title: "Advanced CSS and Sass: Flexbox, Grid, Animations",
    category: "Web Development",
    image: "/images/courses/c2.jpg",
    instructor: "Alex Johnson",
    rating: 4.9,
    reviewCount: 1245,
    price: 74.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "28h 30m",
    badges: ["Top Rated"],
  },
  {
    id: 12,
    title: "Full-Stack JavaScript: Node.js, Express, MongoDB",
    category: "Web Development",
    image: "/images/courses/c3.jpg",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 932,
    price: 89.99,
    originalPrice: 179.99,
    level: "Intermediate",
    duration: "32h 45m",
    badges: ["Bestseller"],
  },
];

export const popularCategoriesData = [
  {
    name: "Web Development",
    count: 425,
    image: "/images/courses/c1.jpg",
  },
  {
    name: "Data Science",
    count: 320,
    image: "/images/courses/c2.jpg",
  },
  {
    name: "Mobile Development",
    count: 275,
    image: "/images/courses/c3.jpg",
  },
  {
    name: "Design",
    count: 245,
    image: "/images/courses/c1.jpg",
  },
  {
    name: "Marketing",
    count: 180,
    image: "/images/courses/c2.jpg",
  },
  {
    name: "Cloud Computing",
    count: 165,
    image: "/images/courses/c3.jpg",
  },
];

export const allCoursesData = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    category: "Web Development",
    subcategory: "Full-Stack",
    image: "/images/courses/c3.jpg",
    instructor: "Alex Johnson",
    rating: 4.8,
    reviewCount: 1245,
    price: 89.99,
    originalPrice: 199.99,
    level: "All Levels",
    duration: "42h 30m",
    badges: ["Bestseller", "Top Rated"],
    description:
      "A comprehensive bootcamp covering HTML, CSS, JavaScript, Node.js, and more to turn you into a full-stack web developer.",
  },
  {
    id: 5,
    title: "The Complete React Developer Course",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c2.jpg",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 1089,
    price: 84.99,
    originalPrice: 169.99,
    level: "Intermediate",
    duration: "30h 10m",
    badges: ["Bestseller"],
    description:
      "Learn React by building real projects. Master modern React features including hooks, context API, and Redux.",
  },
  {
    id: 11,
    title: "Advanced CSS and Sass: Flexbox, Grid, Animations",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c1.jpg",
    instructor: "Alex Johnson",
    rating: 4.9,
    reviewCount: 1245,
    price: 74.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "28h 30m",
    badges: ["Top Rated"],
    description:
      "Take your CSS skills to the next level. Master flexbox, CSS Grid, responsive design, and advanced animations.",
  },
  {
    id: 12,
    title: "Full-Stack JavaScript: Node.js, Express, MongoDB",
    category: "Web Development",
    subcategory: "Backend",
    image: "/images/courses/c3.jpg",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 932,
    price: 89.99,
    originalPrice: 179.99,
    level: "Intermediate",
    duration: "32h 45m",
    badges: ["Bestseller"],
    description:
      "Build complete backend applications with Node.js, Express, and MongoDB. Includes authentication, API design, and deployment.",
  },
  {
    id: 13,
    title: "Vue.js - The Complete Guide",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c2.jpg",
    instructor: "Sarah Chen",
    rating: 4.9,
    reviewCount: 876,
    price: 79.99,
    originalPrice: 159.99,
    level: "All Levels",
    duration: "26h 15m",
    badges: ["Bestseller"],
    description:
      "Master Vue.js from the ground up. Learn Vue 3, Vuex, Vue Router, and how to build single-page applications.",
  },
  {
    id: 14,
    title: "PHP & MySQL - Complete Web Development Course",
    category: "Web Development",
    subcategory: "Backend",
    image: "/images/courses/c1.jpg",
    instructor: "David Miller",
    rating: 4.6,
    reviewCount: 732,
    price: 69.99,
    originalPrice: 139.99,
    level: "Beginner",
    duration: "34h 20m",
    badges: [],
    description:
      "Learn PHP and MySQL to build dynamic, database-driven websites. Includes practical projects and security best practices.",
  },
  {
    id: 15,
    title: "Responsive Web Design Masterclass",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c3.jpg",
    instructor: "Emma Wilson",
    rating: 4.7,
    reviewCount: 654,
    price: 59.99,
    originalPrice: 119.99,
    level: "All Levels",
    duration: "18h 45m",
    badges: [],
    description:
      "Create websites that look great on any device. Master media queries, flexbox, CSS Grid, and responsive images.",
  },
  {
    id: 16,
    title: "Angular - The Complete Guide",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c2.jpg",
    instructor: "Thomas Clark",
    rating: 4.8,
    reviewCount: 921,
    price: 84.99,
    originalPrice: 169.99,
    level: "Intermediate",
    duration: "33h 30m",
    badges: ["Top Rated"],
    description:
      "Comprehensive course on Angular framework. Learn to build sophisticated SPAs with TypeScript and Angular.",
  },
  {
    id: 17,
    title: "Modern JavaScript From The Beginning",
    category: "Web Development",
    subcategory: "JavaScript",
    image: "/images/courses/c1.jpg",
    instructor: "Alex Johnson",
    rating: 4.9,
    reviewCount: 1184,
    price: 69.99,
    originalPrice: 139.99,
    level: "All Levels",
    duration: "21h 50m",
    badges: ["Bestseller"],
    description:
      "Learn modern JavaScript from the fundamentals to advanced topics like ES6+, asynchronous JS, and the DOM.",
  },
  {
    id: 18,
    title: "GraphQL with Node.js - The Complete Guide",
    category: "Web Development",
    subcategory: "Backend",
    image: "/images/courses/c3.jpg",
    instructor: "Sarah Chen",
    rating: 4.7,
    reviewCount: 687,
    price: 79.99,
    originalPrice: 159.99,
    level: "Intermediate",
    duration: "24h 15m",
    badges: ["Hot & New"],
    description:
      "Master GraphQL API development with Node.js. Learn schema design, resolvers, authentication, and performance optimization.",
  },
  {
    id: 19,
    title: "Web Accessibility - Build Inclusive Websites",
    category: "Web Development",
    subcategory: "Frontend",
    image: "/images/courses/c2.jpg",
    instructor: "Emma Wilson",
    rating: 4.8,
    reviewCount: 532,
    price: 64.99,
    originalPrice: 129.99,
    level: "Intermediate",
    duration: "16h 20m",
    badges: [],
    description:
      "Learn how to make websites accessible to everyone. Master WCAG guidelines, ARIA, keyboard navigation, and testing.",
  },
  {
    id: 20,
    title: "TypeScript for Web Developers",
    category: "Web Development",
    subcategory: "JavaScript",
    image: "/images/courses/c1.jpg",
    instructor: "Michael Brown",
    rating: 4.9,
    reviewCount: 743,
    price: 74.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "19h 45m",
    badges: ["Top Rated"],
    description:
      "Comprehensive TypeScript course for web developers. Learn type safety, interfaces, generics, and integration with frameworks.",
  },
];

export const categoryInfoData = {
  "web-development": {
    title: "Web Development Courses",
    description:
      "Master the skills needed to build modern, responsive websites and web applications. Learn frontend technologies like HTML, CSS, and JavaScript, as well as backend development with Node.js, Python, PHP, and more.",
    image: "/images/courses/c3.jpg",
    subcategories: [
      "Frontend",
      "Backend",
      "Full-Stack",
      "JavaScript",
      "React",
      "Vue.js",
      "Angular",
      "Node.js",
      "PHP",
    ],
    stats: [
      { label: "Students", value: "425K+" },
      { label: "Courses", value: 150 },
      { label: "Instructors", value: 48 },
      { label: "Job Growth", value: "23%" },
    ],
  },
  "data-science": {
    title: "Data Science Courses",
    description:
      "Learn to analyze complex data, build machine learning models, and derive meaningful insights. Courses cover Python, R, statistics, visualization, and AI techniques to help you excel in this high-demand field.",
    image: "/images/courses/c2.jpg",
    subcategories: [
      "Machine Learning",
      "Deep Learning",
      "Python",
      "R",
      "Data Analysis",
      "Data Visualization",
      "Statistics",
    ],
    stats: [
      { label: "Students", value: "320K+" },
      { label: "Courses", value: 120 },
      { label: "Instructors", value: 35 },
      { label: "Job Growth", value: "31%" },
    ],
  },
  "mobile-development": {
    title: "Mobile Development Courses",
    description:
      "Build native and cross-platform mobile applications for iOS and Android. Master frameworks like React Native, Flutter, Swift, and Kotlin to create engaging mobile experiences.",
    image: "/images/courses/c1.jpg",
    subcategories: [
      "iOS",
      "Android",
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
    ],
    stats: [
      { label: "Students", value: "275K+" },
      { label: "Courses", value: 80 },
      { label: "Instructors", value: 28 },
      { label: "Job Growth", value: "20%" },
    ],
  },
  design: {
    title: "Design Courses",
    description:
      "Develop your creative skills and learn industry-standard design tools and principles. Courses cover UI/UX design, graphic design, web design, and more to help you create beautiful digital experiences.",
    image: "/images/courses/c3.jpg",
    subcategories: [
      "UI/UX",
      "Graphic Design",
      "Web Design",
      "Adobe Creative Suite",
      "Figma",
      "Sketch",
    ],
    stats: [
      { label: "Students", value: "245K+" },
      { label: "Courses", value: 95 },
      { label: "Instructors", value: 32 },
      { label: "Job Growth", value: "18%" },
    ],
  },
};
