export const coursesData = [
  {
    id: 1,
    title: "Complete Web Development Bootcamp",
    category: "Web Development",
    image: "/api/placeholder/400/225",
    instructor: "Alex Johnson",
    rating: 4.8,
    reviewCount: 1245,
    price: 89.99,
    originalPrice: 199.99,
    level: "All Levels",
    duration: "42h 30m",
    badges: ["Bestseller", "Top Rated"],
  },
  {
    id: 2,
    title: "Advanced JavaScript: From Fundamentals to Functional JS",
    category: "JavaScript",
    image: "/api/placeholder/400/225",
    instructor: "Sarah Chen",
    rating: 4.9,
    reviewCount: 982,
    price: 79.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "28h 15m",
    badges: ["Hot & New"],
  },
  {
    id: 3,
    title: "Flutter & Dart: The Complete Guide",
    category: "Mobile Development",
    image: "/api/placeholder/400/225",
    instructor: "Mark Williams",
    rating: 4.7,
    reviewCount: 843,
    price: 94.99,
    originalPrice: 189.99,
    level: "Beginner",
    duration: "32h 45m",
    badges: ["Bestseller"],
  },
  {
    id: 4,
    title: "Machine Learning A-Z: Hands-On Python & R",
    category: "Data Science",
    image: "/api/placeholder/400/225",
    instructor: "Jessica Taylor",
    rating: 4.6,
    reviewCount: 1532,
    price: 129.99,
    originalPrice: 199.99,
    level: "Advanced",
    duration: "45h 20m",
    badges: ["Highest Rated"],
  },
  {
    id: 5,
    title: "The Complete React Developer Course",
    category: "Web Development",
    image: "/api/placeholder/400/225",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 1089,
    price: 84.99,
    originalPrice: 169.99,
    level: "Intermediate",
    duration: "30h 10m",
    badges: ["Bestseller"],
  },
  {
    id: 6,
    title: "UX & UI Design Masterclass",
    category: "Design",
    image: "/api/placeholder/400/225",
    instructor: "Emma Wilson",
    rating: 4.7,
    reviewCount: 756,
    price: 69.99,
    originalPrice: 139.99,
    level: "All Levels",
    duration: "24h 30m",
  },
  {
    id: 7,
    title: "AWS Certified Solutions Architect",
    category: "Cloud Computing",
    image: "/api/placeholder/400/225",
    instructor: "David Miller",
    rating: 4.9,
    reviewCount: 1342,
    price: 119.99,
    originalPrice: 229.99,
    level: "Advanced",
    duration: "38h 15m",
    badges: ["Highest Rated", "Bestseller"],
  },
  {
    id: 8,
    title: "Python for Data Science and Machine Learning",
    category: "Data Science",
    image: "/api/placeholder/400/225",
    instructor: "Rebecca Lee",
    rating: 4.8,
    reviewCount: 982,
    price: 89.99,
    originalPrice: 179.99,
    level: "Intermediate",
    duration: "36h 45m",
    badges: ["Top Rated"],
  },
  {
    id: 9,
    title: "The Complete Digital Marketing Course",
    category: "Marketing",
    image: "/api/placeholder/400/225",
    instructor: "Thomas Clark",
    rating: 4.6,
    reviewCount: 1120,
    price: 94.99,
    originalPrice: 189.99,
    level: "Beginner",
    duration: "32h 15m",
  },
  {
    id: 10,
    title: "iOS App Development with Swift",
    category: "Mobile Development",
    image: "/api/placeholder/400/225",
    instructor: "Jennifer Roberts",
    rating: 4.7,
    reviewCount: 876,
    price: 99.99,
    originalPrice: 199.99,
    level: "Intermediate",
    duration: "34h 20m",
  },
  {
    id: 11,
    title: "Advanced CSS and Sass: Flexbox, Grid, Animations",
    category: "Web Development",
    image: "/api/placeholder/400/225",
    instructor: "Alex Johnson",
    rating: 4.9,
    reviewCount: 1245,
    price: 74.99,
    originalPrice: 149.99,
    level: "Intermediate",
    duration: "28h 30m",
    badges: ["Top Rated"],
  },
  {
    id: 12,
    title: "Full-Stack JavaScript: Node.js, Express, MongoDB",
    category: "Web Development",
    image: "/api/placeholder/400/225",
    instructor: "Michael Brown",
    rating: 4.8,
    reviewCount: 932,
    price: 89.99,
    originalPrice: 179.99,
    level: "Intermediate",
    duration: "32h 45m",
    badges: ["Bestseller"],
  },
];

export const popularCategoriesData = [
  {
    name: "Web Development",
    count: 425,
    image: "/api/placeholder/300/200",
  },
  {
    name: "Data Science",
    count: 320,
    image: "/api/placeholder/300/200",
  },
  {
    name: "Mobile Development",
    count: 275,
    image: "/api/placeholder/300/200",
  },
  {
    name: "Design",
    count: 245,
    image: "/api/placeholder/300/200",
  },
  {
    name: "Marketing",
    count: 180,
    image: "/api/placeholder/300/200",
  },
  {
    name: "Cloud Computing",
    count: 165,
    image: "/api/placeholder/300/200",
  },
];
